use std::{collections::HashMap, env, fs, path::PathBuf};

use serde::Deserialize;

// ── Schema (mirrors core/src/palette.rs) ────────────────────────────────────

#[derive(Deserialize)]
struct PaletteFile {
    name:        String,
    #[allow(dead_code)]
    description: Option<String>,
    #[allow(dead_code)]
    url:         Option<String>,
    colors:      Vec<ColorEntry>,
}

#[derive(Deserialize)]
#[serde(untagged)]
enum ColorEntry {
    Plain(String),
    Named(HashMap<String, String>),
}

// ── Hex validation ───────────────────────────────────────────────────────────

fn is_valid_hex(hex: &str) -> bool {
    let s = hex.trim_start_matches('#');
    (s.len() == 6 || s.len() == 3) && s.chars().all(|c| c.is_ascii_hexdigit())
}

// ── Build script ─────────────────────────────────────────────────────────────

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let palettes_dir = PathBuf::from(&manifest_dir).join("../palettes");

    // Collect and sort YAML files.
    let mut yaml_files: Vec<PathBuf> = fs::read_dir(&palettes_dir)
        .unwrap_or_else(|e| {
            panic!(
                "build error: cannot read palettes directory '{}': {e}",
                palettes_dir.display()
            )
        })
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("yaml"))
        .collect();

    yaml_files.sort();

    // Re-run the build script if any palette file changes.
    println!("cargo:rerun-if-changed={}", palettes_dir.display());
    for path in &yaml_files {
        println!("cargo:rerun-if-changed={}", path.display());
    }

    // Validate each file and collect (slug, content) pairs.
    let mut entries: Vec<(String, String)> = Vec::with_capacity(yaml_files.len());

    for path in &yaml_files {
        let content = fs::read_to_string(path)
            .unwrap_or_else(|e| panic!("build error: cannot read '{}': {e}", path.display()));

        // --- structural validation ---
        let parsed: PaletteFile = serde_yaml::from_str(&content).unwrap_or_else(|e| {
            panic!("build error: invalid YAML in '{}': {e}", path.display())
        });

        if parsed.name.trim().is_empty() {
            panic!("build error: '{}': 'name' field is empty", path.display());
        }

        if parsed.colors.is_empty() {
            panic!(
                "build error: '{}': 'colors' list is empty",
                path.display()
            );
        }

        // --- per-color hex validation ---
        for (i, entry) in parsed.colors.iter().enumerate() {
            let hex: &str = match entry {
                ColorEntry::Plain(h) => h.as_str(),
                ColorEntry::Named(map) => {
                    let (_, h) = map.iter().next().unwrap_or_else(|| {
                        panic!(
                            "build error: '{}': color at index {i} is an empty map",
                            path.display()
                        )
                    });
                    h.as_str()
                }
            };

            if !is_valid_hex(hex) {
                panic!(
                    "build error: '{}': color at index {i} has invalid hex '{hex}'",
                    path.display()
                );
            }
        }

        let slug = path.file_stem().unwrap().to_string_lossy().to_string();
        entries.push((slug, content));
    }

    // --- code generation ---
    // Written to src/ (not OUT_DIR) so rust-analyzer can resolve it without
    // needing to evaluate env!("OUT_DIR") at analysis time.
    let mut code = String::from("// @generated — do not edit by hand (regenerated by build.rs)\n");
    code.push_str("const EMBEDDED: &[(&str, &str)] = &[\n");
    for (slug, content) in &entries {
        // {:?} produces a properly escaped Rust string literal.
        code.push_str(&format!("    ({slug:?}, {content:?}),\n"));
    }
    code.push_str("];\n");

    let out_path = PathBuf::from(&manifest_dir).join("src/palettes_generated.rs");
    fs::write(&out_path, code)
        .unwrap_or_else(|e| panic!("build error: cannot write generated palettes: {e}"));
}
