[package]
name        = "palettify-core"
version     = "0.1.0"
edition     = "2021"
description = "Core image color palette mapping library"
authors     = ["Roberto Coratti <corattiroberto@gmail.com>"]

[dependencies]
image      = "0.25"
rayon      = "1"
serde      = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
thiserror  = "1"
tracing    = "0.1"
