use std::path::PathBuf;

use clap::Parser;
use image::ImageFormat;
use palettify_core::{algorithm::Algorithm, palette::Palette, processor::process_image};

// ── Embedded palettes (generated by build.rs from palettes/*.yaml) ───────────

include!(concat!(env!("OUT_DIR"), "/palettes_generated.rs"));

fn palette_names() -> String {
    EMBEDDED.iter().map(|(n, _)| *n).collect::<Vec<_>>().join(", ")
}

fn load_builtin(name: &str) -> Palette {
    let content = EMBEDDED
        .iter()
        .find(|(n, _)| *n == name)
        .map(|(_, c)| *c)
        .unwrap_or_else(|| {
            eprintln!("error: palette '{name}' not found. Available: {}", palette_names());
            std::process::exit(1);
        });
    Palette::from_yaml(content).expect("pre-validated by build.rs")
}

// ── CLI definition ───────────────────────────────────────────────────────────

#[derive(Parser)]
#[command(name = "palettify", version, about = "Remap image colors to a palette", arg_required_else_help = true)]
struct Cli {
    /// Source image (PNG, JPEG, WebP, ...) — required unless --list-palettes / --show-palette
    input: Option<PathBuf>,

    /// List all built-in palettes and exit
    #[arg(short = 'l', long)]
    list_palettes: bool,

    /// Show all colors in a built-in palette and exit
    #[arg(long, value_name = "NAME")]
    show_palette: Option<String>,

    /// Built-in palette name (e.g. nord, dracula)
    #[arg(short, long)]
    palette: Option<String>,

    /// Custom palette file (.yaml)
    #[arg(long)]
    palette_file: Option<PathBuf>,

    /// Output file [default: <input stem>-palettified.<format>]
    #[arg(short, long)]
    output: Option<PathBuf>,

    /// Output format: png | jpg | webp
    #[arg(short, long, default_value = "png")]
    format: String,

    /// Algorithm: nearest | floyd-steinberg | ordered
    #[arg(short, long, default_value = "nearest")]
    algo: String,
}

// ── Helpers ──────────────────────────────────────────────────────────────────

/// Print a true-color block using ANSI 24-bit background escape codes.
/// Falls back gracefully on terminals that don't support it.
fn color_swatch(r: u8, g: u8, b: u8) -> String {
    format!("\x1b[48;2;{r};{g};{b}m    \x1b[0m")
}

// ── Entry point ──────────────────────────────────────────────────────────────

fn main() {
    let cli = Cli::parse();

    // --list-palettes
    if cli.list_palettes {
        println!("{:<25}  COLORS", "PALETTE");
        println!("{}", "-".repeat(35));
        for (slug, content) in EMBEDDED {
            let p = Palette::from_yaml(content).expect("pre-validated by build.rs");
            let desc = p.description.as_deref().unwrap_or("");
            println!("{:<25}  {:>2}   {}", slug, p.color_count(), desc);
        }
        return;
    }

    // --show-palette <name>
    if let Some(ref name) = cli.show_palette {
        let p = load_builtin(name);
        println!(
            "{} — {} colors",
            p.name,
            p.color_count()
        );
        if let Some(desc) = &p.description {
            println!("{desc}");
        }
        if let Some(url) = &p.url {
            println!("{url}");
        }
        println!();
        for color in &p.colors {
            let swatch = color_swatch(color.r, color.g, color.b);
            let hex    = color.hex();
            let label  = color.name.as_deref().unwrap_or("—");
            println!("  {}  {}  {}", swatch, hex, label);
        }
        return;
    }

    // Require <INPUT> for processing.
    let input = cli.input.unwrap_or_else(|| {
        eprintln!("error: <INPUT> is required. Use --list-palettes to see available palettes.");
        std::process::exit(1);
    });

    // Resolve palette.
    let palette = match (&cli.palette, &cli.palette_file) {
        (Some(name), _) => {
            let content = EMBEDDED
                .iter()
                .find(|(n, _)| n == name)
                .map(|(_, c)| *c)
                .unwrap_or_else(|| {
                    eprintln!("error: palette '{name}' not found. Available: {}", palette_names());
                    std::process::exit(1);
                });
            Palette::from_yaml(content).unwrap_or_else(|e| {
                eprintln!("error: failed to load palette '{name}': {e}");
                std::process::exit(1);
            })
        }
        (None, Some(path)) => {
            Palette::from_file(path).unwrap_or_else(|e| {
                eprintln!("error: failed to load palette file '{}': {e}", path.display());
                std::process::exit(1);
            })
        }
        (None, None) => {
            eprintln!("error: provide --palette <name> or --palette-file <file>. Available: {}", palette_names());
            std::process::exit(1);
        }
    };

    // Resolve algorithm.
    let algorithm = cli.algo.parse::<Algorithm>().unwrap_or_else(|_| {
        eprintln!("error: unknown algorithm '{}'. Valid values: nearest, floyd-steinberg, ordered", cli.algo);
        std::process::exit(1);
    });

    // Load image.
    let img = image::open(&input).unwrap_or_else(|e| {
        eprintln!("error: could not open '{}': {e}", input.display());
        std::process::exit(1);
    });

    // Process.
    let result = process_image(img, &palette, algorithm);

    // Resolve output format.
    let (image_format, ext) = match cli.format.to_lowercase().as_str() {
        "jpg" | "jpeg" => (ImageFormat::Jpeg, "jpg"),
        "webp"         => (ImageFormat::WebP, "webp"),
        _              => (ImageFormat::Png,  "png"),
    };

    // Resolve output path.
    let output = cli.output.unwrap_or_else(|| {
        let stem = input.file_stem().unwrap_or_default().to_string_lossy();
        input.with_file_name(format!("{stem}-palettified.{ext}"))
    });

    image::DynamicImage::ImageRgb8(result)
        .save_with_format(&output, image_format)
        .unwrap_or_else(|e| {
            eprintln!("error: could not write '{}': {e}", output.display());
            std::process::exit(1);
        });

    println!("saved: {}", output.display());
}
